from __future__ import annotations
import hashlib,json,sys
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
from joblib import Parallel,delayed
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
PROJECT_ROOT=Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:sys.path.insert(0,str(PROJECT_ROOT))
from scripts.train_speech_model import LABELS,discover_tess,discover_crema,discover_emodb
split_path=PROJECT_ROOT/'models/speech/wavlm_clean_split_v3.json';log_path=PROJECT_ROOT/'outputs/speech/wavlm_clean_v3_validation_sweep.jsonl';summary_path=PROJECT_ROOT/'models/speech/wavlm_clean_v3_weighted_fusion_summary.json';split=json.loads(split_path.read_text(encoding='utf8'));assert split['test_status']=='sealed'
samples=discover_tess(PROJECT_ROOT/'datasets/TESS')+discover_crema(PROJECT_ROOT/'datasets/CREMA-D')+discover_emodb(PROJECT_ROOT/'datasets/EmoDB');sp=np.array([s.speaker for s in samples]);y=np.array([LABELS.index(s.label) for s in samples]);X=np.load(PROJECT_ROOT/'models/speech/wavlm_clean_v2_layer_stats.npy',mmap_mode='r');tr=np.flatnonzero(np.isin(sp,split['train_speakers']));va=np.flatnonzero(np.isin(sp,split['val_speakers']));used=[LABELS.index(x) for x in split['emotion_labels']]
fusions=[((5,7),w) for w in ((.25,.75),(.4,.6),(.5,.5),(.6,.4),(.75,.25))]+[((5,7,9),w) for w in ((.5,.3,.2),(.4,.4,.2),(.4,.3,.3),(.33,.34,.33),(.3,.4,.3),(.25,.5,.25))]
def eval_one(layers,weights,C=3.,gf=.25,weight=None,stage='weight_probe'):
 fused=sum(float(w)*np.asarray(X[:,l,:1536],np.float32) for l,w in zip(layers,weights));sc=StandardScaler();Xt=sc.fit_transform(fused[tr]);Xv=sc.transform(fused[va]);m=SVC(C=C,gamma=gf/Xt.shape[1],class_weight=weight,cache_size=1024,random_state=2026);m.fit(Xt,y[tr]);p=m.predict(Xv);rep=classification_report(y[va],p,labels=used,target_names=split['emotion_labels'],output_dict=True,zero_division=0);cfg={'layers':layers,'weights':weights,'C':C,'gamma_factor':gf,'class_weight':weight,'stage':stage};rid=hashlib.sha256(json.dumps(cfg,sort_keys=True).encode()).hexdigest()[:16]
 return {'run_id':rid,'protocol_name':'wavlm_clean_v3','split_file':str(split_path.resolve()),'used_test_set':False,'dataset_names':split['dataset_names'],'emotion_labels':split['emotion_labels'],'random_seed':2026,'train_speakers_count':len(split['train_speakers']),'val_speakers_count':len(split['val_speakers']),'test_speakers_count':len(split['test_speakers']),'train_sample_count':split['train_sample_count'],'val_sample_count':split['val_sample_count'],'test_sample_count':split['test_sample_count'],'wavlm_model_name':'microsoft/wavlm-base-plus','wavlm_layers':list(layers),'layer_fusion':'weighted_average','layer_weights':list(weights),'pooling':'mean_std','feature_dim':1536,'classifier':'rbf_svm','C':C,'gamma':gf,'class_weight':weight,'scaler_type':'StandardScaler fitted on train only','augmentation_enabled':False,'augmentation_config':{'name':'none'},'val_accuracy':float(accuracy_score(y[va],p)),'val_macro_f1':float(f1_score(y[va],p,average='macro')),'val_weighted_f1':float(f1_score(y[va],p,average='weighted')),'val_per_class_precision':{x:float(rep[x]['precision']) for x in split['emotion_labels']},'val_per_class_recall':{x:float(rep[x]['recall']) for x in split['emotion_labels']},'val_per_class_f1':{x:float(rep[x]['f1-score']) for x in split['emotion_labels']},'val_confusion_matrix':confusion_matrix(y[va],p,labels=used).tolist(),'model_save_path':None,'created_at':datetime.now(timezone.utc).isoformat(),'notes':f'Weighted layer-fusion {stage}; validation only; v3 test sealed.'}
probe=Parallel(n_jobs=4,prefer='threads')(delayed(eval_one)(l,w,3.,.25,cw) for l,w in fusions for cw in (None,'balanced'));winner=max(probe,key=lambda r:(r['val_macro_f1'],r['val_accuracy']));layers=tuple(winner['wavlm_layers']);weights=tuple(winner['layer_weights']);refine=Parallel(n_jobs=4,prefer='threads')(delayed(eval_one)(layers,weights,C,g,cw,'local_refine') for C in (2.,3.,5.) for g in (.125,.25,.375) for cw in (None,'balanced'));records=probe+refine
with log_path.open('a',encoding='utf8') as f:
 for r in records:f.write(json.dumps(r,ensure_ascii=False)+'\n')
best=max(records,key=lambda r:(r['val_macro_f1'],r['val_accuracy']));summary={'protocol_name':'wavlm_clean_v3','used_test_set':False,'test_status':split['test_status'],'candidate_count':len(records),'best':best,'created_at':datetime.now(timezone.utc).isoformat()};summary_path.write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({k:best[k] for k in ('run_id','wavlm_layers','layer_weights','C','gamma','class_weight','val_accuracy','val_macro_f1')},ensure_ascii=False,indent=2))
