from __future__ import annotations
import argparse,json
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def args():
 p=argparse.ArgumentParser();p.add_argument('--split-file',type=Path,default=ROOT/'models/speech/wavlm_clean_split_v3.json');p.add_argument('--output-jsonl',type=Path,default=ROOT/'outputs/speech/wavlm_clean_v3_validation_sweep.jsonl');p.add_argument('--output-summary',type=Path,default=ROOT/'models/speech/wavlm_clean_v3_validation_summary.json');p.add_argument('--frozen-plan',type=Path,default=ROOT/'models/speech/wavlm_clean_v3_frozen_evaluation_plan.json');p.add_argument('--final-results',type=Path,default=ROOT/'models/speech/wavlm_clean_v3_final_results.json');p.add_argument('--output-report',type=Path,default=ROOT/'outputs/speech/wavlm_clean_v3_report.md');return p.parse_args()
def pct(x):return f'{100*x:.2f}%'
def main():
 a=args();split=json.loads(a.split_file.read_text(encoding='utf8'));summary=json.loads(a.output_summary.read_text(encoding='utf8'));plan=json.loads(a.frozen_plan.read_text(encoding='utf8'));result=json.loads(a.final_results.read_text(encoding='utf8'));labels=split['emotion_labels'];zh={'anger':'愤怒','disgust':'厌恶','fear':'恐惧','joy':'高兴','sadness':'悲伤','neutral':'中性'};matrix=result['test_confusion_matrix'];confusions=[]
 for i,row in enumerate(matrix):
  for j,n in enumerate(row):
   if i!=j and n:confusions.append((n,labels[i],labels[j]))
 confusions.sort(reverse=True);v2_acc=.7390;v2_f1=.7354
 lines=['# WavLM clean v3 说话人独立评估报告','', '## 1. 实验目的','', '在不读取、不重评、不污染 WavLM clean v2 测试集的前提下，重新建立 clean v3 说话人独立协议，验证多层 WavLM 融合、池化、分类器、类别权重及训练集轻量增强能否提升泛化性能。','', '## 2. v3 数据划分','',f'- 数据集：{", ".join(split["dataset_names"])}',f'- 情绪：{", ".join(zh[x] for x in labels)}',f'- 固定随机种子：{split["random_seed"]}',f'- 说话人：训练 {len(split["train_speakers"])}、验证 {len(split["val_speakers"])}、测试 {len(split["test_speakers"])}',f'- 样本：训练 {split["train_sample_count"]}、验证 {split["val_sample_count"]}、测试 {split["test_sample_count"]}',f'- v2 测试说话人：全部 {split["v2_test_exclusion_count"]} 名从 v3 三个分区排除', '- 三个说话人集合经过断言验证，完全互斥。','', '### 各分区类别分布','', '| 分区 | 愤怒 | 厌恶 | 恐惧 | 高兴 | 悲伤 | 中性 |','|---|---:|---:|---:|---:|---:|---:|']
 for key,name in [('train','训练'),('validation','验证'),('test','测试')]:
  d=split['per_split_class_distribution'][key];lines.append(f'| {name} | '+ ' | '.join(str(d[x]) for x in labels)+' |')
 lines += ['', '## 3. TESS 排除原因','', 'TESS 只有两名说话人，无法同时构成说话人互斥的训练、验证、测试三部分，因此不纳入 v3。','', '## 4. 测试集封存','',f'- 调参期间状态：`sealed`',f'- 冻结计划声明：{plan["statement"]}',f'- 最终状态：`{split["test_status"]}`', '- 验证搜索代码不构造测试索引；冻结计划落盘后才允许一次性测试。','', '## 5. 验证候选配置概览','',f'- 去重候选数：{summary["candidate_count"]}', '- 涵盖：单层与多层融合、mean/mean+std、RBF-SVM、LogisticRegression、LinearSVC、balanced 对照、训练集样本权重、训练集波形增强及 RBF-SVM 决策集成。', '- 波形增强仅用于训练集；验证集和测试集未增强。','', '## 6. 验证 Macro-F1 Top 10','', '| 排名 | Run ID | 层/成员 | Pooling | 分类器 | C | Gamma | 权重 | Val Accuracy | Val Macro-F1 |','|---:|---|---|---|---|---:|---|---|---:|---:|']
 for i,r in enumerate(summary['top_10'],1):
  layers=','.join(r.get('ensemble_members',[])) or str(r.get('wavlm_layers'));lines.append(f'| {i} | `{r["run_id"]}` | {layers} | {r["pooling"]} | {r["classifier"]} | {r.get("C")} | {r.get("gamma")} | {r.get("class_weight")} | {pct(r["val_accuracy"])} | {pct(r["val_macro_f1"])} |')
 s=plan['selected_config'];lines += ['', '## 7. 最佳冻结配置','',f'- Run ID：`{plan["selected_run_id"]}`',f'- 成员：{", ".join(s["ensemble_members"])}',f'- 决策权重：{s["ensemble_weights"]}', '- 成员定义：', '  - `l7`：layer 7，mean+std，C=3，gamma=0.5/feature_dim，非 balanced', '  - `l57b`：layers [5,7] 等权特征融合，mean+std，C=3，gamma=0.25/feature_dim，balanced', '  - `l579w`：layers [5,7,9] 按 [0.5,0.3,0.2] 特征融合，mean+std，C=3，gamma=0.25/feature_dim，非 balanced',f'- 验证 Accuracy：{pct(plan["validation_results"]["accuracy"])}',f'- 验证 Macro-F1：{pct(plan["validation_results"]["macro_f1"])}','- 增强：关闭；训练集增强验证结果更差。','', '## 8. 最终一次性测试结果','',f'- Accuracy：**{pct(result["test_accuracy"])}**',f'- Macro-F1：**{pct(result["test_macro_f1"])}**',f'- Weighted-F1：**{pct(result["test_weighted_f1"])}**',f'- 测试样本：{result["test_sample_count"]}',f'- 测试说话人：{result["test_speakers_count"]}',f'- 模型 SHA-256：`{result["model_hash"]}`',f'- 特征缓存 SHA-256：`{result["feature_cache_hash"]}`','', '## 9. 与 v2 最佳结果对比','', '| 协议 | 模型 | Test Accuracy | Test Macro-F1 | 说明 |','|---|---|---:|---:|---|',f'| clean v2 | 单模型 layer 7 mean+std balanced RBF-SVM | {pct(v2_acc)} | {pct(v2_f1)} | 数值来自任务背景中的既有 v2 证据，未重新评估 v2 测试集 |',f'| clean v3 | 三成员 RBF-SVM 决策集成 | {pct(result["test_accuracy"])} | {pct(result["test_macro_f1"])} | 新测试说话人，一次性评估 |',f'| v3-v2 | — | {100*(result["test_accuracy"]-v2_acc):+.2f} pp | {100*(result["test_macro_f1"]-v2_f1):+.2f} pp | 不同测试划分，仅作独立证据对照 |','', '## 10. 逐类测试指标','', '| 类别 | Precision | Recall | F1 | Support |','|---|---:|---:|---:|---:|']
 for x in labels:lines.append(f'| {zh[x]} | {pct(result["test_per_class_precision"][x])} | {pct(result["test_per_class_recall"][x])} | {pct(result["test_per_class_f1"][x])} | {result["test_per_class_support"][x]} |')
 lines += ['', '## 11. 混淆矩阵','', '行是真实类别，列是预测类别。','', '| 真实\\预测 | '+' | '.join(zh[x] for x in labels)+' |','|---|'+'---:|'*len(labels)]
 for x,row in zip(labels,matrix):lines.append('| '+zh[x]+' | '+' | '.join(map(str,row))+' |')
 lines += ['', '## 12. 错误分析','']
 for n,src,dst in confusions[:6]:lines.append(f'- {zh[src]} → {zh[dst]}：{n} 条')
 weakest=sorted(labels,key=lambda x:result['test_per_class_f1'][x])[:2];lines += [f'- 最弱类别：{"、".join(zh[x] for x in weakest)}。建议未来优先增加这些类别的多说话人、自然语音数据，而不是继续针对 v3 测试集调参。','', '## 13. 部署建议','', '**暂不替换 v2 部署模型。** v3 提供了独立的约 73.5% Macro-F1 复现证据，但测试 Accuracy 略低于 v2，Macro-F1 基本持平，同时三成员集成推理与打包成本更高。保留 v3 模型和证据文件，用于研究对照。','', '## 14. 后续实验边界','', '**如果继续调参，必须建立 clean v4 新测试集。不得继续使用 v3 测试结果修改模型、权重或超参数。**','', '## 证据文件','',f'- Split：`{a.split_file}`',f'- Validation JSONL：`{a.output_jsonl}`',f'- Validation summary：`{a.output_summary}`',f'- Frozen plan：`{a.frozen_plan}`',f'- Final results：`{a.final_results}`',f'- Final model：`{result["model_path"]}`']
 a.output_report.parent.mkdir(parents=True,exist_ok=True);a.output_report.write_text('\n'.join(lines)+'\n',encoding='utf8');print({'report':str(a.output_report),'lines':len(lines)})
if __name__=='__main__':main()
