from __future__ import annotations
import hashlib,json,sys
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
from joblib import Parallel,delayed
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from scripts.train_speech_model import LABELS,discover_tess,discover_crema,discover_emodb
spfile=ROOT/'models/speech/wavlm_clean_split_v3.json';split=json.loads(spfile.read_text(encoding='utf8'));assert split['test_status']=='sealed';meta=json.loads((ROOT/'models/speech/wavlm_clean_v3_train_augmented_metadata.json').read_text(encoding='utf8'));assert not meta['used_test_set'] and meta['source_partition']=='train only';samples=discover_tess(ROOT/'datasets/TESS')+discover_crema(ROOT/'datasets/CREMA-D')+discover_emodb(ROOT/'datasets/EmoDB');sp=np.array([s.speaker for s in samples]);y=np.array([LABELS.index(s.label) for s in samples]);X=np.load(ROOT/'models/speech/wavlm_clean_v2_layer_stats.npy',mmap_mode='r');aug=np.load(ROOT/'models/speech/wavlm_clean_v3_train_augmented.npy',mmap_mode='r');tr=np.array(meta['source_indices']);va=np.flatnonzero(np.isin(sp,split['val_speakers']));assert len(tr)==len(aug)==split['train_sample_count'];fused=.5*np.asarray(X[:,5,:],np.float32)+.3*np.asarray(X[:,7,:],np.float32)+.2*np.asarray(X[:,9,:],np.float32);train=np.concatenate([fused[tr],np.asarray(aug,np.float32)]);target=np.concatenate([y[tr],y[tr]]);sc=StandardScaler();Xt=sc.fit_transform(train);Xv=sc.transform(fused[va]);used=[LABELS.index(x) for x in split['emotion_labels']]
def one(aw,C=3.,gf=.25,cw=None,stage='probe'):
 weights=np.concatenate([np.ones(len(tr)),np.full(len(tr),aw)]);m=SVC(C=C,gamma=gf/Xt.shape[1],class_weight=cw,cache_size=1536,random_state=2026);m.fit(Xt,target,sample_weight=weights);p=m.predict(Xv);rep=classification_report(y[va],p,labels=used,target_names=split['emotion_labels'],output_dict=True,zero_division=0);cfg={'aug_weight':aw,'C':C,'gamma':gf,'class_weight':cw,'stage':stage};rid=hashlib.sha256(json.dumps(cfg,sort_keys=True).encode()).hexdigest()[:16]
 return {'run_id':rid,'protocol_name':'wavlm_clean_v3','split_file':str(spfile.resolve()),'used_test_set':False,'dataset_names':split['dataset_names'],'emotion_labels':split['emotion_labels'],'random_seed':2026,'train_speakers_count':len(split['train_speakers']),'val_speakers_count':len(split['val_speakers']),'test_speakers_count':len(split['test_speakers']),'train_sample_count':split['train_sample_count'],'val_sample_count':split['val_sample_count'],'test_sample_count':split['test_sample_count'],'wavlm_model_name':'microsoft/wavlm-base-plus','wavlm_layers':[5,7,9],'layer_fusion':'weighted_average','layer_weights':[.5,.3,.2],'pooling':'mean_std','feature_dim':1536,'classifier':'rbf_svm','C':C,'gamma':gf,'class_weight':cw,'scaler_type':'StandardScaler fitted on original+augmented train only','augmentation_enabled':True,'augmentation_config':meta['augmentation_config']|{'augmented_sample_weight':aw},'val_accuracy':float(accuracy_score(y[va],p)),'val_macro_f1':float(f1_score(y[va],p,average='macro')),'val_weighted_f1':float(f1_score(y[va],p,average='weighted')),'val_per_class_precision':{x:float(rep[x]['precision']) for x in split['emotion_labels']},'val_per_class_recall':{x:float(rep[x]['recall']) for x in split['emotion_labels']},'val_per_class_f1':{x:float(rep[x]['f1-score']) for x in split['emotion_labels']},'val_confusion_matrix':confusion_matrix(y[va],p,labels=used).tolist(),'model_save_path':None,'created_at':datetime.now(timezone.utc).isoformat(),'notes':f'Train-only waveform augmentation {stage}; v3 test sealed.'}
probe=Parallel(n_jobs=4,prefer='threads')(delayed(one)(aw,3.,.25,cw) for aw in (.25,.5,.75,1.) for cw in (None,'balanced'));winner=max(probe,key=lambda r:r['val_macro_f1']);refine=[]
if winner['val_macro_f1']>.6946362215876657:
 aw=winner['augmentation_config']['augmented_sample_weight'];refine=Parallel(n_jobs=4,prefer='threads')(delayed(one)(aw,C,g,cw,'local_refine') for C in (2.,3.,5.) for g in (.125,.25,.375) for cw in (None,'balanced'))
rows=probe+refine;log=ROOT/'outputs/speech/wavlm_clean_v3_validation_sweep.jsonl'
with log.open('a',encoding='utf8') as f:
 for r in rows:f.write(json.dumps(r,ensure_ascii=False)+'\n')
best=max(rows,key=lambda r:(r['val_macro_f1'],r['val_accuracy']));(ROOT/'models/speech/wavlm_clean_v3_augmentation_summary.json').write_text(json.dumps({'used_test_set':False,'test_status':split['test_status'],'best':best,'rows':rows},ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({k:best[k] for k in ('run_id','augmentation_config','C','gamma','class_weight','val_accuracy','val_macro_f1')},ensure_ascii=False,indent=2))
